/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaredecadatsro;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rafael
 */
public class TelaCad extends javax.swing.JFrame {

    /**
     * Creates new form TelaCad
     */
    public TelaCad() { // Classe principal do programa .
        initComponents();
        DefaultTableModel modelo = ( DefaultTableModel) lblTab.getModel(); // repete o modelo da tabela que foi criada para este programa
        lblTab.setRowSorter(new TableRowSorter(modelo)); // usar  o modelo ds tabela ( DefaultTableModel ) dentro desse método.  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblTab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblDat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        MenuArq = new javax.swing.JMenu();
        MenuMod = new javax.swing.JMenu();
        SubMenuVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        lblTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Preço", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lblTab);

        jLabel1.setText("Produto:");

        jLabel2.setText("Preço:");

        txtPre.setText("0");

        jLabel3.setText("Quantidade:");

        txtQtd.setText("0");

        jLabel4.setText("Cod:");

        txtCod.setText("0");

        btnDel.setText("Deletar");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar Cadastro");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel7.setText("Data:");

        jLabel5.setText("Hora:");

        MenuArq.setText("Arquivo");
        BarraMenu.add(MenuArq);

        MenuMod.setText("Modos");

        SubMenuVenda.setText("Venda");
        SubMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuVendaActionPerformed(evt);
            }
        });
        MenuMod.add(SubMenuVenda);

        BarraMenu.add(MenuMod);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        // TODO add your handling code here:
        DefaultTableModel produtos = (DefaultTableModel) lblTab.getModel(); // a variável produtos está linkada a tabela através dessa "herança" .
        Object[] dados = {txtProd.getText(),txtQtd.getText(),txtPre.getText(),txtCod.getText() };
        produtos.addRow(dados); // addrow adiciona dados na tabela .
        
        
        
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed

       /*  System.out.println(" row selecionado" +lblTab.getSelectedRow() ); O método GETSELECTROW seleciona a linha da tanela
      para deletar im dado , e quando estiver com o status de de -1 , é porque não tem item (linha) selecionado. */
       
     if (lblTab.getSelectedRow() != -1) { // caso aconteça a seleção na linha da tabela , o item será deletado.
         DefaultTableModel produtos = (DefaultTableModel) lblTab.getModel();  
      produtos.removeRow(lblTab.getSelectedRow());
     } else {
         JOptionPane.showMessageDialog(null," Para excluir um produto , é necessário \n  seleciona-lo . " , "Atenção!  "
                 , JOptionPane.INFORMATION_MESSAGE);
         
     }
     
     
     
     
     
     
      
      
       
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here: 
       if (lblTab.getSelectedRow() != -1) {// condicional caso uma linha da tabela esteja selecionada .
           lblTab.setValueAt(txtProd.getText() , lblTab.getSelectedRow() , 0 ); // Após a lihha selecionada , reescreve o valor da variável no (  vetor - casa de indice 0 ) 
           lblTab.setValueAt(txtQtd.getText(), lblTab.getSelectedRow() , 1); // Após a lihha selecionada , reescreve o valor da variável no (  vetor - casa de indice 1 )
           lblTab.setValueAt(txtPre.getText() , lblTab.getSelectedRow(), 2); // Após a lihha selecionada , reescreve o valor da variável no (  vetor - casa de indice 2 )
           lblTab.setValueAt(txtCod.getText() , lblTab.getSelectedRow () , 3); // Após a lihha selecionada , reescreve o valor da variável no (  vetor - casa de indice 4 )
           
           
       }
            
        DefaultTableModel editpro = (DefaultTableModel) lblTab.getModel();
          lblTab.setValueAt(txtQtd.getText(), lblTab.getSelectedRow() , 1);
    }//GEN-LAST:event_btnEditActionPerformed

    private void lblTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTabMouseClicked
        // TODO add your handling code here:
      if (lblTab.getSelectedRow() != -1) { // condicional caso uma linha da tabela esteja selecionada .
          txtProd.setText(lblTab.getValueAt(lblTab.getSelectedRow() , 0 ).toString()); // seleciona o dado da linha da tabela e mostrta nos campo (  vetor - casa de indice 0 ) 
          txtQtd.setText(lblTab.getValueAt(lblTab.getSelectedRow (), 1  ). toString());// seleciona o dado da linha da tabela e mostrta nos campo ( vetor - casa  de indice 1 )
          txtPre.setText(lblTab.getValueAt(lblTab.getSelectedRow() , 2 ). toString()); // seleciona o dado da linha da tabela e mostrta nos campo ( vetor - casa  de indice 2 )
          txtCod.setText(lblTab.getValueAt(lblTab.getSelectedRow(), 3).toString() ) ; // seleciona o dado da linha da tabela e mostrta nos campo ( vetor - casa  de indice 3)   
      
      }  
      
       
    }//GEN-LAST:event_lblTabMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Quando a janela principal abrir , aparecera a instrução abaixo :
        
        // data
         Date  dataSis =  new Date ();
         SimpleDateFormat formato = new SimpleDateFormat ("dd/ MM/yyyy");
         lblDat.setText(formato.format(dataSis));
         
         //hora 
         Timer timer = new Timer ( 1000, new hora ());
         timer.start ();
         
         
        
        
    }//GEN-LAST:event_formWindowOpened

    private void SubMenuVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuVendaActionPerformed
        // TODO add your handling code here:
        Vender v = new Vender ();
        v.setVisible(true);
        
       
    }//GEN-LAST:event_SubMenuVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu MenuArq;
    private javax.swing.JMenu MenuMod;
    private javax.swing.JMenuItem SubMenuVenda;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDat;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTable lblTab;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtPre;
    private javax.swing.JTextField txtProd;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener {
          
           @Override  // subscrição de um método que já existe ( evita confiltos )
           public void actionPerformed( ActionEvent  e ) {
                 Calendar now = Calendar.getInstance();
                    lblHora.setText(String.format("%1$tH:%1$tM:%1$tS" , now ));
                    
    
           }
    
} 
 
}

